# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fcdc2b2a489eb7fdeade98c544a729053d6638b3e1fab3078d581834ef94f68606a12a92efa305ca5bb55f3e59cd86478fdebf317dee9984627f92807e5eb89

test:
  secret_key_base: d5e910e30970a1a4e7a2a8d1b6fc75cf16114d4cda399767527c46f1606a246989888a996b2b1d7ce5f1a63b8011f9b33cfab8ea21fc267bdcdfe4760499761e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
